name: Auto Commit Scheduled

on:
  schedule:
    - cron: "0 * * * *" 
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  

      - name: Modify LAST_UPDATED file
        run: |
          echo "Last scheduled update on $(date)" > LAST_UPDATED

      - name: Commit changes (if any)
        run: |
          git config user.email "nerddevlabs@gmail.com"
          git config user.name "thruvsol"
          git add LAST_UPDATED
          if ! git diff --staged --quiet; then
            git commit -m "chore(bot): auto update activity"
          else
            echo "No changes to commit."
          fi

      - name: Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # pakai token resmi untuk push
          git push https://x-access-token:${GH_TOKEN}@github.com/thruvsol/greening-day.git HEAD:main
